### ISSUE TITLE
use the sqitch.sh to improve speed of travis

### ISSUE THREAD

**Issue by pyramation** [constructive-io/launchql-v1#9]
Trying to get travis to work with this 
```yml
language: node_js
notifications:
  email: false
node_js:
  - node
services:
  - docker
env:
  global:
    - PGPORT=7777
    - PGDATABASE=testing-db
    - PGTEMPLATE_DATABASE=testing-template-db
    - PGHOST=localhost
    - PGPASSWORD=
    - PGUSER=postgres
    - TMPDIR=/tmp
  matrix:
    - PACKAGE=packages/db-testing
    - PACKAGE=packages/db-transform
    - PACKAGE=packages/db-utils
before_install:
  - mkdir -p $HOME/bin
  - wget https://raw.githubusercontent.com/launchql/launchql-docker/master/helpers/sqitch.sh && mv sqitch.sh $HOME/bin/sqitch && chmod +x $HOME/bin/sqitch
  - docker run -p 7777:5432 --name postgres -d postgres:10.3
  - sleep 3
  - while ! docker exec -it postgres pg_isready -U postgres -h 127.0.0.1; do echo "$(date) - waiting for database to start"; sleep 1; done
script:
  - yarn
  - yarn bootstrap
  - yarn build
  - cd $PACKAGE
  - yarn test
```
